name: Keep Railway Alive
on:
  schedule:
    - cron: "*/15 * * * *"  # Runs every 5 minutes

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Railway App
        run: curl -s https://satyanaam-food-backend.up.railway.app/ > /dev/null
